services:
  - type: web
    name: spillburg-portal
    env: python
    plan: free
    region: singapore
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
